name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código do repositório
      uses: actions/checkout@v2

    - name: Configurar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    - name: Baixar dependências do Maven
      run: mvn install -DskipTests

    - name: Rodar os testes
      run: mvn test

    - name: Fazer upload dos relatórios de teste
      uses: actions/upload-artifact@v2
      with:
        name: relatórios-cucumber
        path: target/cucumber-reports/*.json
