name: Selenium Java Cucumber CI

on:
  push:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # Passo 2: Configurar o Java 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Passo 3: Instalar o Chrome e o ChromeDriver automaticamente
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1

      # Passo 4: Executar os testes com Maven
      - name: Run tests with Maven
        run: mvn clean test

      # Passo 5: Publicar o relatório HTML como artefato
      - name: Upload Cucumber HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: target/cucumber-reports/cucumber.html

      # Passo 6: Publicar o relatório JSON como artefato (opcional)
      - name: Upload Cucumber JSON Report
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-json-report
          path: target/cucumber-reports/cucumber.json
